### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jlb30504** [tsmgeek/ExifTool_PHP_Stayopen#10]
This is not an issue but a question from a newby.  Can this be run under Apache since PCNTL is not normally used with Apache?  Suggestions welcomed.

Sorry to contact you this way but couldn't find another route.

**Comment by tsmgeek** [comment]
Yes it can but you not the best way to do it as its slow to start up perl each time. PCNTL is really only needed for long running background scripts. 
Consider using a job queue system like gearman if you plan to use it quite a bit as it will have a big speedup.
