### ISSUE TITLE
Call to undefined function pcntl_signal()

### ISSUE THREAD

**Issue by speich** [tsmgeek/ExifTool_PHP_Stayopen#2]
pcntl_signal() is not available on windows. Maybe you can mention in the readme, that  ExifTool_PHP_Stayopen only works on nix.

**Comment by tsmgeek** [comment]
Noted, ile put a fix in for this.
If you want you can just remove the calls to pcntl_signal() and the script should still work on windows I hope.

**Comment by speich** [comment]
I'll try and let you know.

**Comment by speich** [comment]
I commented out the two calls to pcntl on line 124 and 125. Unfortunately I always end up in an endless do-while loop on 222 and have to restart apache. Any ideas?

**Comment by tsmgeek** [comment]
It would only loop around 222 if you have turned on stream mode and for some reason no data has come back from exiftool, essentially it loops around until it sees a response with $endstr which is the only way to figure out where the data ends.

I personally use fgets as its just as fast but far lower CPU and prevents getting stuck in long loops.
