### ISSUE TITLE
Errors from PCNTL

### ISSUE THREAD

**Issue by vipers-web-design** [tsmgeek/ExifTool_PHP_Stayopen#8]
I can't pinpoint the error, because there is an infinite loop and I ended up crashing my hosting server temporarily.

I don't have PCNTL enabled/installed. Otherwise my MacBook would crash.

**Comment by tsmgeek** [comment]
If you dont have pcntl then all it should do it flag a warning when you first init the class, other than that it should not cause any problems. If you do not use pcntl then the library will not be able to handle situations where exiftool may crash or if for some reason the OS kills the process.

If you have any error outputs let me know.

**Comment by vipers-web-design** [comment]
I cannot pinpoint the error, there is an infinite loop somewhere when I run $exif->test($data); and $exif-add($data); that causes my error_log to continuously gets populated (see image for size in MB)

This returns that I have successfully located ExifTools and is running (on both localhost and on my server)
```
$exif = \Exiftool\ ExifToolBatch::getInstance( "Image-ExifTool-11.75/exiftool" );
if ( $exif ) {
  print( 'EXIF is running' );
} else {
  print( 'EXIF is **NOT** running' );
}
```
*** But after that***
<img width="447" alt="Screen Shot 2019-11-09 at 1 54 58 PM" src="https://user-images.githubusercontent.com/8532498/68534312-b0d33c80-02f8-11ea-9e91-7a6110b9ad24.png">

This is just locally, yes, I do see
```
[09-Nov-2019 13:46:49 America/Chicago] PHP Notice:  pcntl extension is not loaded in /ExifTool_PHP_Stayopen-master/src/ExifToolBatch.php on line 79
```

I upload the page with all this to my server and try to load it -- the loading 'favicon' keeps on spinning and the error_log does not even get created.

**Comment by tsmgeek** [comment]
Did you get this sorted?

**Comment by vipers-web-design** [comment]
I haven't used this since November. I don't think I did.
