### ISSUE TITLE
Option "-extension" does not work

### ISSUE THREAD

**Issue by FireLizard** [tsmgeek/ExifTool_PHP_Stayopen#9]
When passing the option [-ext](https://exiftool.org/exiftool_pod.html#Processing-control) the result is not the expected one

By executing
```php
$exif = ExifToolBatch::getInstance('/usr/bin/exiftool');
$exif->add([
    '-recurse',
    '-ext PDF',
    '/path/to/all/files/',
]);
$output = $exif->fetchAllDecoded(true);
```
the output includes all files with any extension instead of only PDF-files.

Furthermore when using these options above only the key `SourceFile` was returned. If leaving `-ext PDF` than the output includes all tags/metadata of each file. :-\

_My environment_
- php 7.2.15
- exiftool 10.40

Hopefully you can help me :)

**Comment by FireLizard** [comment]
**Solved**

In cause of [-@ ARGFILE](https://exiftool.org/exiftool_pod.html#Other-options) each argument has to be on a separate line ... meaning I have to pass it like so:
```php
$exif->add([
    '-recurse',
    '-ext', // split all options ...
    'PDF',  // ... requiring additional args
    '/path/to/all/files/',
]);
```
Then its working ;)

**Comment by tsmgeek** [comment]
Thanks for update, yes that one caught me out in the past too. Limitation of the CLI args.
